name = "ThesisLean"
version = "0.1.0"
defaultTargets = ["thesislean"]

[[lean_lib]]
name = "ThesisLean"

[[lean_exe]]
name = "thesislean"
root = "Main"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
